### ISSUE TITLE
Cemu update does not work

### ISSUE THREAD

**Issue by alexandrgorodilov** [Fs00/CemuUpdateTool#1]
Relevant for version 2.1

I am upgrading Cemu from version 1.13.1 to 1.13.2. After downloading the archive, the program can not open it.
![image](https://user-images.githubusercontent.com/16904814/46754146-29715f00-ccdb-11e8-9760-f2bb29487d82.png)

**Comment by Fs00** [comment]
This happened to me too. That's because [cemu.info/releases/cemu_1.13.2.zip](cemu.info/releases/cemu_1.13.2.zip) is corrupted. No program can open it.
Cemu developers have uploaded the hotfix 1.13.2d at [this link](cemu.info/releases/cemu_1.13.2d.zip), which can not be detected by the program due to how the update search algorithm works (it doesn't look for b,c,d hotfixes since Cemu devs usually replace the base version zip).
