### ISSUE TITLE
Suggtions 

### ISSUE THREAD

**Issue by Nintendocustom** [Fs00/CemuUpdateTool#2]
Can you add cemuhook(https://cemuhook.sshnuke.net/) and this cemu updater tool(https://github.com/nosklo/cemu_utils/releases)?

**Comment by Fs00** [comment]
CemuHook automatic download is a feature which I wanted to add, but it would require a lot of work because I can't reuse the same algorithm I've developed for Cemu due to how CemuHook archives are named on their server. The only solution is parsing the HTML, which is not easy to implement and also not very reliable: if CemuHook homepage changes significantly, it won't work anymore.
Regarding cemutil, it would be easier but honestly not worth IMO, you can see that it hasn't been worked on for months and it's basically abandoned from its developer.
